[package]
name = "marks"
version = "0.1.0"
authors = ["Taisuke Miyazaki <imishinist@gmail.com>"]
edition = "2018"
description = "line marking cli tool"

[dependencies]
termcolor = "1.0.4"
regex = "1.1.6"
clap = "2.33.0"
lazy_static = "1.3.0"
