Output assets/demo.gif

Set Theme "Aardvark Blue"
Set FontSize 23
Set Width 1200
Set Height 720

Hide
Type "marks edit README.md --reset"
Enter
Sleep 100ms

Show

Type@100ms "marks view README.md"
Enter

Sleep 2s

Type@100ms "jjjjj"
Sleep 200ms

Type@200ms "mmmmm"
Sleep 2s

Type "/"
Sleep 300ms

Type@140ms "normal"
Enter

Sleep 10s

Type@300ms "nnnn"
Sleep 3s

Type@200ms "mmmmmm"
Sleep 3s

Type "G"
Sleep 2s

Type "N"
Sleep 3s

Type "q"

Sleep 3s

